site_name: Ollama Proxy
site_description: A proxy server that translates Ollama API calls to OpenRouter API calls
site_author: Ollama Proxy Contributors
site_url: https://github.com/your-username/ollama-proxy

# Repository
repo_name: your-username/ollama-proxy
repo_url: https://github.com/your-username/ollama-proxy

# Copyright
copyright: Copyright &copy; 2025 Ollama Proxy Contributors

# Configuration
theme:
  name: material
  language: en
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - navigation.footer
    - toc.follow
    - toc.integrate
    - search.suggest
    - search.highlight
    - search.share
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
  custom_dir: docs/overrides

# Plugins
plugins:
  - search

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/your-username/ollama-proxy
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/ollama-proxy/

extra_css:
  - css/custom.css

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
  - Home: index.md
  - Getting Started:
      - Introduction: index.md
      - Installation: index.md#installation
      - Configuration: configuration.md
      - Usage Examples: usage-examples.md
  - API Reference: api-reference.md
  - Deployment:
      - Deployment Guide: deployment.md
      - Docker: deployment.md#docker-deployment-recommended
      - Systemd: deployment.md#systemd-deployment-linux
      - Kubernetes: deployment.md#kubernetes-deployment
  - Architecture: architecture.md
  - Troubleshooting: troubleshooting.md
  - Contributing: contributing.md