global:
  scrape_interval: 10s
  evaluation_interval: 10s
  external_labels:
    environment: "staging"

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # Ollama Proxy application
  - job_name: "ollama-proxy"
    static_configs:
      - targets: ["ollama-proxy:11434"]
    metrics_path: "/metrics"
    scrape_interval: 15s
    scrape_timeout: 10s

  # Health check endpoint
  - job_name: "ollama-proxy-health"
    static_configs:
      - targets: ["ollama-proxy:11434"]
    metrics_path: "/health"
    scrape_interval: 10s
    scrape_timeout: 5s

  # Redis metrics
  - job_name: "redis"
    static_configs:
      - targets: ["redis:6379"]
    metrics_path: "/metrics"
    scrape_interval: 15s
